// Manually written instance file for the GQA-packed vector kernel (not generated by generate_cu_files.py).

#include "../fattn-vec-gqa.cuh"

DECL_FATTN_VEC_GQA_CASE(256, 2, GGML_TYPE_Q4_0, GGML_TYPE_Q4_0);
DECL_FATTN_VEC_GQA_CASE(256, 6, GGML_TYPE_Q4_0, GGML_TYPE_Q4_0);
